### ISSUE TITLE
[doc] Issue in "Components Versions"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#274]
Components Versions:

https://suse-edge.github.io/id-release-notes.html#id-components-versions

Would Cert-Manager version need to be included?

**Comment by ranjinimn** [comment]
@e-minguez Can you please let  me know if I can include the version details for Cert-Manager in our documentation? Can you please provide the following details that can be included? 
Name: cert-manager
Version
Helm Chart Version
Artifact Location (URL/Image)

**Comment by hardys** [comment]
As mentioned in #279 it appears the Rancher reccomendation is to install the latest ref https://github.com/rancher/rancher-docs/pull/924 and I don't think we currently have any downstream version to reference - this makes cert-manger an indirect dependency rather than an edge component, so I'll close this for now - in future we can perhaps revisit if/when there is a downstream cert-manager chart we can consume.
